services:
  - type: web
    name: sbif-florist-poc
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PLAID_CLIENT_ID
        sync: false
      - key: PLAID_SECRET
        sync: false
      - key: PLAID_ENV
        value: sandbox
      - key: PLAID_REDIRECT_URI
        sync: false
